// Central content for the site. Edit here to update what shows across pages.

export const profile = {
  name: "Rian Butala",
  firstName: "Rian",
  lastName: "Butala",
  title: "Rian Butala · AI/ML · Robotics Software",
  kicker: "INCOMING AT UCLA · ROBOTICS SOFTWARE LEAD · AI/ML RESEARCH",
  headline:
    "I reimplement modern ML from the papers up: diffusion, JEPA world models, and LLMs built from scratch in PyTorch. Then I build the perception systems and apps that put them to work.",
  shortBio:
    "Incoming UCLA CS, AI/ML researcher and robotics software lead. I build diffusion models, world models, and LLMs from scratch, plus the perception systems and apps around them.",
  about:
    "I optimize for efficiency: getting models to train fast, fit in tight budgets, and run on the hardware I have. Most of my work is reimplementing recent papers from scratch to understand them end to end, then building real systems on top.",
  location: "Los Angeles, CA",
  email: "rianbutala@gmail.com",
  resume: "/resume.pdf",
};

export type Social = {
  name: string;
  href: string;
};

export const socials: Social[] = [
  { name: "GitHub", href: "https://github.com/flappybird1084" },
  { name: "Hugging Face", href: "https://huggingface.co/flappybird1084" },
  { name: "LinkedIn", href: "https://www.linkedin.com/in/rianbutala" },
  { name: "Email", href: "mailto:rianbutala@gmail.com" },
];

export type Focus = {
  index: string;
  title: string;
  description: string;
};

export const focus: Focus[] = [
  {
    index: "01",
    title: "Deep learning, from scratch",
    description:
      "Diffusion (rectified-flow latent), JEPA world models, and LLMs reimplemented from the papers up in PyTorch.",
  },
  {
    index: "02",
    title: "Vision & perception systems",
    description:
      "Facial recognition, autonomous surveillance, and VLM-driven captioning and anomaly analysis over live video.",
  },
  {
    index: "03",
    title: "Full-stack & tooling",
    description:
      "Health and productivity apps, agent platforms, and developer tooling, down to a GPU monitor for macOS PyTorch.",
  },
];

export const stack: { label: string; items: string[] }[] = [
  {
    label: "ML / RESEARCH",
    items: [
      "PyTorch",
      "CUDA",
      "Diffusion",
      "JEPA",
      "Quantization / QAT",
      "Computer vision",
      "YOLO",
      "VLMs",
    ],
  },
  { label: "LANGUAGES", items: ["Python", "C++", "Java", "TypeScript"] },
  {
    label: "SYSTEMS & WEB",
    items: ["FastAPI", "Flask", "Next.js", "ArduPilot"],
  },
];

export type Project = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  tech: string;
  href: string;
  image?: string;
  imageAlt?: string;
  award?: string;
  liveDemo?: { label: string; href: string };
};

export const projects: Project[] = [
  {
    slug: "latent-diffusion",
    name: "Latent diffusion from scratch",
    tagline: "Rectified-flow latent diffusion, MMDiT-style, written from the paper up.",
    description:
      "Rectified-flow latent diffusion in an MMDiT-style architecture, written from the paper up. The fifth iteration over eight months: earlier attempts wouldn't train stably until I rebuilt the data pipeline. The live demo samples 256px images from my trained checkpoint.",
    tech: "PyTorch",
    href: "https://github.com/flappybird1084/sd-v5",
    image: "/img/sdv5-demo.webp",
    imageAlt: "Snowy mountain landscape generated by the latent diffusion model",
    liveDemo: { label: "Live demo", href: "https://huggingface.co/spaces/flappybird1084/sd-v5" },
  },
  {
    slug: "homegrown-llm",
    name: "Homegrown LLM",
    tagline: "A transformer LM pretrained from scratch, then instruction-tuned.",
    description:
      "A transformer language model pretrained from scratch, then instruction-tuned. The third in an eight-month line of from-scratch LMs, after an autocomplete model and a first chat model. Chat with it in the live demo.",
    tech: "PyTorch",
    href: "https://github.com/flappybird1084/thonk-v1",
    image: "/img/thonk.png",
    imageAlt: "Homegrown LLM text-generation playground",
    liveDemo: { label: "Live demo", href: "https://huggingface.co/spaces/flappybird1084/chatbot" },
  },
  {
    slug: "parameter-golf",
    name: "OpenAI Parameter Golf",
    tagline: "Best language model under 16 MB: 1.5126 bits/byte in 600 seconds.",
    description:
      "OpenAI's challenge to train the best language model under 16 MB. Mine reached 1.5126 bits/byte in a 600-second window on a single A5000.",
    tech: "PyTorch",
    href: "https://github.com/flappybird1084/parameter-golf",
    image: "/img/golf.jpg",
    imageAlt:
      "Parameter Golf training log: 600s wallclock, int8+zlib 9.6MB artifact, sliding-window BPB ~1.51",
  },
  {
    slug: "vjepa-world-model",
    name: "V-JEPA world model",
    tagline: "A self-supervised video world model hand-written in PyTorch.",
    description:
      "A self-supervised video world model (V-JEPA) hand-written from scratch in PyTorch. Training was stable, no representation collapse and loss converging, though I did not run downstream evaluation.",
    tech: "PyTorch",
    href: "https://github.com/flappybird1084/wm2",
  },
  {
    slug: "otter-agent",
    name: "OtterAgent",
    tagline: "A social network where AI agents negotiate on your behalf.",
    description:
      "A social network where AI agents negotiate on your behalf, managing calendars, notes, and tasks under scoped permissions. Won Best AI Hack at Synthesis Hacks @ Google.",
    tech: "FastAPI · Gemini",
    href: "https://github.com/flappybird1084/otter-agent",
    image: "/img/otter-agent.png",
    imageAlt: "OtterAgent brain-map interface with an agent chat panel",
    award: "Best AI Hack",
    liveDemo: { label: "Devpost", href: "https://devpost.com/software/otterbox-h1fbi7" },
  },
  {
    slug: "vesta",
    name: "Vesta, surveillance engine",
    tagline: "Multi-camera theft detection with YOLO triggers and VLM threat scoring.",
    description:
      "Built for Stratford Preparatory to deter and detect theft across multiple cameras. YOLO triggers recording on people; a vision-language model scores each clip for threats and makes them searchable in plain language. Runs entirely on local hardware, no cloud.",
    tech: "Flask · YOLO",
    href: "https://github.com/flappybird1084/vesta",
    image: "/img/vesta.png",
    imageAlt: "Vesta recordings library with AI threat scores",
  },
  {
    slug: "btop-macos-gpu",
    name: "btop, with macOS GPU",
    tagline: "GPU telemetry in btop for Apple-Silicon PyTorch users, no sudo.",
    description:
      "GPU telemetry in btop for Apple-Silicon PyTorch users, no sudo required.",
    tech: "C++",
    href: "https://github.com/flappybird1084/btop-macos-gpu",
    image: "/img/btop.png",
    imageAlt: "btop showing M3 Max CPU and GPU usage on macOS",
  },
];

export type Experience = {
  role: string;
  org: string;
  description: string;
  period: string;
};

export const experience: Experience[] = [
  {
    role: "Research Assistant",
    org: "UCLA",
    description:
      "Invited as a high school senior to analyze neural recordings and optimize decision transformers with graduate students and faculty.",
    period: "2026 - now",
  },
  {
    role: "Software Engineer",
    org: "WakeMates",
    description:
      "Sole developer taking the product from concept to deployment alongside the founder.",
    period: "2026 - now",
  },
  {
    role: "Founding Software Lead & Captain",
    org: "FRC 10252 / FTC 21781",
    description:
      "Built a rookie team's full codebase from scratch and mentored members in computer vision and autonomous path planning.",
    period: "2022 - 2026",
  },
  {
    role: "Founding VP, Aerospace Club",
    org: "Stratford Preparatory",
    description:
      "Built and flew autonomous long-range RC aircraft from scratch. Pixhawk, ArduPilot, ExpressLRS.",
    period: "2025 - 2026",
  },
  {
    role: "AI/ML Intern",
    org: "FinanceGPT",
    description: "Machine learning research and applied work over a summer internship.",
    period: "2024",
  },
];

export type Education = {
  school: string;
  description: string;
  period: string;
};

export const education: Education[] = [
  {
    school: "UCLA",
    description: "B.S. Computer Science.",
    period: "2026 - 2030",
  },
  {
    school: "Stratford Preparatory",
    description: "National Merit Finalist. Robotics, Aerospace Engineering, Tennis.",
    period: "2022 - 2026",
  },
];
